blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions or Discussions
    url: https://github.com/bassetlamraoui/progres-algeria-extension/discussions
    about: Use this if you have a question, opinion, or want to share ideas.
