name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What's your idea?
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Why is it useful?
      placeholder: Explain how this would help users or improve the extension
